// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq5p0wS_jATbnRzbVl4nyaTNhP2qjyasg',
    appId: '1:74827843986:web:89db03eda024491473594b',
    messagingSenderId: '74827843986',
    projectId: 'qwash-8af9e',
    authDomain: 'qwash-8af9e.firebaseapp.com',
    storageBucket: 'qwash-8af9e.firebasestorage.app',
    measurementId: 'G-Y93D4SY4FN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAPw9RC9P8rwB1NVuwrBzaNCApw6kY4Es',
    appId: '1:74827843986:android:6b14d29cf44fa61473594b',
    messagingSenderId: '74827843986',
    projectId: 'qwash-8af9e',
    storageBucket: 'qwash-8af9e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq5p0wS_jATbnRzbVl4nyaTNhP2qjyasg',
    appId: '1:74827843986:web:6fbcc6b4eb4a789b73594b',
    messagingSenderId: '74827843986',
    projectId: 'qwash-8af9e',
    authDomain: 'qwash-8af9e.firebaseapp.com',
    storageBucket: 'qwash-8af9e.firebasestorage.app',
    measurementId: 'G-2N0EVFL99C',
  );

}